/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RechercheRouteImport } from './routes/recherche'
import { Route as PrestationsServicesRouteImport } from './routes/prestations-services'
import { Route as MaterielRouteImport } from './routes/materiel'
import { Route as MarquesRouteImport } from './routes/marques'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SousCategoriesSlugRouteImport } from './routes/sous-categories.$slug'
import { Route as SolutionsSlugRouteImport } from './routes/solutions.$slug'
import { Route as SecteursSlugRouteImport } from './routes/secteurs.$slug'
import { Route as ProduitsSlugRouteImport } from './routes/produits.$slug'
import { Route as CategoriesSlugRouteImport } from './routes/categories.$slug'

const RechercheRoute = RechercheRouteImport.update({
  id: '/recherche',
  path: '/recherche',
  getParentRoute: () => rootRouteImport,
} as any)
const PrestationsServicesRoute = PrestationsServicesRouteImport.update({
  id: '/prestations-services',
  path: '/prestations-services',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterielRoute = MaterielRouteImport.update({
  id: '/materiel',
  path: '/materiel',
  getParentRoute: () => rootRouteImport,
} as any)
const MarquesRoute = MarquesRouteImport.update({
  id: '/marques',
  path: '/marques',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SousCategoriesSlugRoute = SousCategoriesSlugRouteImport.update({
  id: '/sous-categories/$slug',
  path: '/sous-categories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsSlugRoute = SolutionsSlugRouteImport.update({
  id: '/solutions/$slug',
  path: '/solutions/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SecteursSlugRoute = SecteursSlugRouteImport.update({
  id: '/secteurs/$slug',
  path: '/secteurs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduitsSlugRoute = ProduitsSlugRouteImport.update({
  id: '/produits/$slug',
  path: '/produits/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesSlugRoute = CategoriesSlugRouteImport.update({
  id: '/categories/$slug',
  path: '/categories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/contact': typeof ContactRoute
  '/marques': typeof MarquesRoute
  '/materiel': typeof MaterielRoute
  '/prestations-services': typeof PrestationsServicesRoute
  '/recherche': typeof RechercheRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/produits/$slug': typeof ProduitsSlugRoute
  '/secteurs/$slug': typeof SecteursSlugRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/sous-categories/$slug': typeof SousCategoriesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/contact': typeof ContactRoute
  '/marques': typeof MarquesRoute
  '/materiel': typeof MaterielRoute
  '/prestations-services': typeof PrestationsServicesRoute
  '/recherche': typeof RechercheRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/produits/$slug': typeof ProduitsSlugRoute
  '/secteurs/$slug': typeof SecteursSlugRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/sous-categories/$slug': typeof SousCategoriesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/contact': typeof ContactRoute
  '/marques': typeof MarquesRoute
  '/materiel': typeof MaterielRoute
  '/prestations-services': typeof PrestationsServicesRoute
  '/recherche': typeof RechercheRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/produits/$slug': typeof ProduitsSlugRoute
  '/secteurs/$slug': typeof SecteursSlugRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/sous-categories/$slug': typeof SousCategoriesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/contact'
    | '/marques'
    | '/materiel'
    | '/prestations-services'
    | '/recherche'
    | '/categories/$slug'
    | '/produits/$slug'
    | '/secteurs/$slug'
    | '/solutions/$slug'
    | '/sous-categories/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/contact'
    | '/marques'
    | '/materiel'
    | '/prestations-services'
    | '/recherche'
    | '/categories/$slug'
    | '/produits/$slug'
    | '/secteurs/$slug'
    | '/solutions/$slug'
    | '/sous-categories/$slug'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/contact'
    | '/marques'
    | '/materiel'
    | '/prestations-services'
    | '/recherche'
    | '/categories/$slug'
    | '/produits/$slug'
    | '/secteurs/$slug'
    | '/solutions/$slug'
    | '/sous-categories/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  ContactRoute: typeof ContactRoute
  MarquesRoute: typeof MarquesRoute
  MaterielRoute: typeof MaterielRoute
  PrestationsServicesRoute: typeof PrestationsServicesRoute
  RechercheRoute: typeof RechercheRoute
  CategoriesSlugRoute: typeof CategoriesSlugRoute
  ProduitsSlugRoute: typeof ProduitsSlugRoute
  SecteursSlugRoute: typeof SecteursSlugRoute
  SolutionsSlugRoute: typeof SolutionsSlugRoute
  SousCategoriesSlugRoute: typeof SousCategoriesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recherche': {
      id: '/recherche'
      path: '/recherche'
      fullPath: '/recherche'
      preLoaderRoute: typeof RechercheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prestations-services': {
      id: '/prestations-services'
      path: '/prestations-services'
      fullPath: '/prestations-services'
      preLoaderRoute: typeof PrestationsServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materiel': {
      id: '/materiel'
      path: '/materiel'
      fullPath: '/materiel'
      preLoaderRoute: typeof MaterielRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marques': {
      id: '/marques'
      path: '/marques'
      fullPath: '/marques'
      preLoaderRoute: typeof MarquesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sous-categories/$slug': {
      id: '/sous-categories/$slug'
      path: '/sous-categories/$slug'
      fullPath: '/sous-categories/$slug'
      preLoaderRoute: typeof SousCategoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/$slug': {
      id: '/solutions/$slug'
      path: '/solutions/$slug'
      fullPath: '/solutions/$slug'
      preLoaderRoute: typeof SolutionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/secteurs/$slug': {
      id: '/secteurs/$slug'
      path: '/secteurs/$slug'
      fullPath: '/secteurs/$slug'
      preLoaderRoute: typeof SecteursSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produits/$slug': {
      id: '/produits/$slug'
      path: '/produits/$slug'
      fullPath: '/produits/$slug'
      preLoaderRoute: typeof ProduitsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$slug': {
      id: '/categories/$slug'
      path: '/categories/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof CategoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  ContactRoute: ContactRoute,
  MarquesRoute: MarquesRoute,
  MaterielRoute: MaterielRoute,
  PrestationsServicesRoute: PrestationsServicesRoute,
  RechercheRoute: RechercheRoute,
  CategoriesSlugRoute: CategoriesSlugRoute,
  ProduitsSlugRoute: ProduitsSlugRoute,
  SecteursSlugRoute: SecteursSlugRoute,
  SolutionsSlugRoute: SolutionsSlugRoute,
  SousCategoriesSlugRoute: SousCategoriesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
